openapi: 3.0.3
info:
  title: Topology Management API
  description: API contracts for topology graph visualization and management
  version: 1.0.0

paths:
  /api/v1/resources/topology/query:
    post:
      summary: Query topology graph data
      operationId: queryTopology
      tags:
        - Topology
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopologyQueryRequest'
      responses:
        '200':
          description: Topology data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_TopologyQueryResponse'

  /api/v1/resources/members/add:
    post:
      summary: Add members to subgraph
      operationId: addMembers
      tags:
        - Members
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembersAddRequest'
      responses:
        '200':
          description: Members added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_MembersAddResponse'
        '400':
          description: Circular reference detected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Error'

  /api/v1/resources/members/remove:
    post:
      summary: Remove members from subgraph
      operationId: removeMembers
      tags:
        - Members
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembersRemoveRequest'
      responses:
        '200':
          description: Members removed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Void'

  /api/v1/resources/members/query:
    post:
      summary: Query paginated member list
      operationId: queryMembers
      tags:
        - Members
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembersQueryRequest'
      responses:
        '200':
          description: Members list retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_PageResult_SubgraphMember'

  /api/v1/resources/members-with-relations/query:
    post:
      summary: Query members with their relationships
      operationId: queryMembersWithRelations
      tags:
        - Members
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MembersQueryRequest'
      responses:
        '200':
          description: Members with relationships retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_TopologyQueryResponse'

  /api/v1/resources/ancestors/query:
    post:
      summary: Query ancestor breadcrumb chain
      operationId: queryAncestors
      tags:
        - Hierarchy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AncestorsQueryRequest'
      responses:
        '200':
          description: Ancestors retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_AncestorNode_Array'

  /api/v1/relationships/create:
    post:
      summary: Create a relationship between resources
      operationId: createRelationship
      tags:
        - Relationships
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipCreateRequest'
      responses:
        '201':
          description: Relationship created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Relationship'

  /api/v1/relationships/update:
    post:
      summary: Update a relationship
      operationId: updateRelationship
      tags:
        - Relationships
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipUpdateRequest'
      responses:
        '200':
          description: Relationship updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Relationship'
        '409':
          description: Version conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Error'

  /api/v1/relationships/delete:
    post:
      summary: Delete a relationship
      operationId: deleteRelationship
      tags:
        - Relationships
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RelationshipDeleteRequest'
      responses:
        '200':
          description: Relationship deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Void'

  /api/v1/relationships/resource/query:
    post:
      summary: Query relationships for a resource
      operationId: queryResourceRelationships
      tags:
        - Relationships
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResourceRelationshipsQueryRequest'
      responses:
        '200':
          description: Relationships retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Relationship_Array'

  /api/v1/relationships/resource/cycle-detection:
    post:
      summary: Detect circular references
      operationId: detectCycles
      tags:
        - Relationships
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CycleDetectionRequest'
      responses:
        '200':
          description: Cycle detection completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_CycleDetectionResponse'

components:
  schemas:
    # Request Schemas
    TopologyQueryRequest:
      type: object
      required:
        - subgraphId
      properties:
        subgraphId:
          type: integer
          format: int64
        depth:
          type: integer
          default: 1
        includeRelationships:
          type: boolean
          default: true
        operatorId:
          type: integer
          format: int64

    MembersAddRequest:
      type: object
      required:
        - subgraphId
        - memberIds
      properties:
        subgraphId:
          type: integer
          format: int64
        memberIds:
          type: array
          items:
            type: integer
            format: int64
        operatorId:
          type: integer
          format: int64

    MembersRemoveRequest:
      type: object
      required:
        - subgraphId
        - memberIds
      properties:
        subgraphId:
          type: integer
          format: int64
        memberIds:
          type: array
          items:
            type: integer
            format: int64
        operatorId:
          type: integer
          format: int64

    MembersQueryRequest:
      type: object
      required:
        - subgraphId
      properties:
        subgraphId:
          type: integer
          format: int64
        page:
          type: integer
          default: 0
        size:
          type: integer
          default: 10
        operatorId:
          type: integer
          format: int64

    AncestorsQueryRequest:
      type: object
      required:
        - resourceId
      properties:
        resourceId:
          type: integer
          format: int64
        operatorId:
          type: integer
          format: int64

    RelationshipCreateRequest:
      type: object
      required:
        - sourceResourceId
        - targetResourceId
        - type
        - direction
        - strength
      properties:
        sourceResourceId:
          type: integer
          format: int64
        targetResourceId:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/RelationshipType'
        direction:
          $ref: '#/components/schemas/RelationshipDirection'
        strength:
          type: integer
          minimum: 1
          maximum: 10
        description:
          type: string
        operatorId:
          type: integer
          format: int64

    RelationshipUpdateRequest:
      type: object
      required:
        - id
        - version
      properties:
        id:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/RelationshipType'
        direction:
          $ref: '#/components/schemas/RelationshipDirection'
        strength:
          type: integer
          minimum: 1
          maximum: 10
        description:
          type: string
        status:
          $ref: '#/components/schemas/RelationshipStatus'
        version:
          type: integer
          format: int64
        operatorId:
          type: integer
          format: int64

    RelationshipDeleteRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        operatorId:
          type: integer
          format: int64

    ResourceRelationshipsQueryRequest:
      type: object
      required:
        - resourceId
      properties:
        resourceId:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/RelationshipType'
        operatorId:
          type: integer
          format: int64

    CycleDetectionRequest:
      type: object
      required:
        - subgraphId
        - candidateMemberIds
      properties:
        subgraphId:
          type: integer
          format: int64
        candidateMemberIds:
          type: array
          items:
            type: integer
            format: int64
        operatorId:
          type: integer
          format: int64

    # Response Schemas
    TopologyQueryResponse:
      type: object
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/TopologyNode'
        edges:
          type: array
          items:
            $ref: '#/components/schemas/TopologyEdge'
        boundaries:
          type: array
          items:
            $ref: '#/components/schemas/SubgraphBoundary'

    MembersAddResponse:
      type: object
      properties:
        addedCount:
          type: integer
        members:
          type: array
          items:
            $ref: '#/components/schemas/SubgraphMember'

    CycleDetectionResponse:
      type: object
      properties:
        hasCycle:
          type: boolean
        cyclePath:
          type: array
          items:
            type: integer
            format: int64
        cycleDescription:
          type: string

    # Entity Schemas
    TopologyNode:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        typeCode:
          type: string
        typeName:
          type: string
        status:
          $ref: '#/components/schemas/ResourceStatus'
        isSubgraph:
          type: boolean
        layer:
          $ref: '#/components/schemas/TopologyLayer'
        attributes:
          type: object
          additionalProperties: true

    TopologyEdge:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sourceId:
          type: integer
          format: int64
        targetId:
          type: integer
          format: int64
        relationshipType:
          $ref: '#/components/schemas/RelationshipType'
        direction:
          $ref: '#/components/schemas/RelationshipDirection'
        strength:
          type: integer
        status:
          $ref: '#/components/schemas/RelationshipStatus'

    SubgraphBoundary:
      type: object
      properties:
        subgraphId:
          type: integer
          format: int64
        memberIds:
          type: array
          items:
            type: integer
            format: int64

    SubgraphMember:
      type: object
      properties:
        id:
          type: integer
          format: int64
        subgraphId:
          type: integer
          format: int64
        memberId:
          type: integer
          format: int64
        memberName:
          type: string
        memberTypeCode:
          type: string
        memberStatus:
          $ref: '#/components/schemas/ResourceStatus'
        addedAt:
          type: string
          format: date-time
        addedBy:
          type: integer
          format: int64

    Relationship:
      type: object
      properties:
        id:
          type: integer
          format: int64
        sourceResourceId:
          type: integer
          format: int64
        targetResourceId:
          type: integer
          format: int64
        type:
          $ref: '#/components/schemas/RelationshipType'
        direction:
          $ref: '#/components/schemas/RelationshipDirection'
        strength:
          type: integer
        status:
          $ref: '#/components/schemas/RelationshipStatus'
        description:
          type: string
        version:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64

    AncestorNode:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        depth:
          type: integer

    # Enums
    RelationshipType:
      type: string
      enum:
        - DEPENDENCY
        - DATA_FLOW
        - API_CALL
        - DEPLOYMENT

    RelationshipDirection:
      type: string
      enum:
        - UNIDIRECTIONAL
        - BIDIRECTIONAL

    RelationshipStatus:
      type: string
      enum:
        - ACTIVE
        - INACTIVE

    ResourceStatus:
      type: string
      enum:
        - RUNNING
        - STOPPED
        - MAINTENANCE
        - OFFLINE

    TopologyLayer:
      type: string
      enum:
        - scenario
        - flow
        - application
        - middleware
        - infrastructure

    # Generic Response Wrappers
    ApiResponse_TopologyQueryResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          $ref: '#/components/schemas/TopologyQueryResponse'
        success:
          type: boolean

    ApiResponse_MembersAddResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          $ref: '#/components/schemas/MembersAddResponse'
        success:
          type: boolean

    ApiResponse_PageResult_SubgraphMember:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
          properties:
            content:
              type: array
              items:
                $ref: '#/components/schemas/SubgraphMember'
            page:
              type: integer
            size:
              type: integer
            totalElements:
              type: integer
            totalPages:
              type: integer
            first:
              type: boolean
            last:
              type: boolean
        success:
          type: boolean

    ApiResponse_AncestorNode_Array:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/AncestorNode'
        success:
          type: boolean

    ApiResponse_Relationship:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          $ref: '#/components/schemas/Relationship'
        success:
          type: boolean

    ApiResponse_Relationship_Array:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/Relationship'
        success:
          type: boolean

    ApiResponse_CycleDetectionResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          $ref: '#/components/schemas/CycleDetectionResponse'
        success:
          type: boolean

    ApiResponse_Void:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        success:
          type: boolean

    ApiResponse_Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        success:
          type: boolean
