openapi: 3.0.3
info:
  title: Agent Management API
  description: API for managing AI agents in op-stack
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/service/v1
    description: Local development server

paths:
  /agents/list:
    post:
      summary: List agents with pagination
      operationId: listAgents
      tags: [Agents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListAgentsRequest'
      responses:
        '200':
          description: Paginated list of agents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentListResponse'

  /agents/get:
    post:
      summary: Get agent by ID
      operationId: getAgent
      tags: [Agents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetAgentRequest'
      responses:
        '200':
          description: Agent details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentDetailResponse'
        '404':
          description: Agent not found

  /agents/create:
    post:
      summary: Create a new agent
      operationId: createAgent
      tags: [Agents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAgentRequest'
      responses:
        '200':
          description: Created agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentDetailResponse'
        '400':
          description: Validation error
        '409':
          description: Name conflict

  /agents/update:
    post:
      summary: Update agent basic info
      operationId: updateAgent
      tags: [Agents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAgentRequest'
      responses:
        '200':
          description: Updated agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentDetailResponse'
        '404':
          description: Agent not found
        '409':
          description: Name conflict
        '423':
          description: Agent is busy

  /agents/config/update:
    post:
      summary: Update agent AI configuration
      operationId: updateAgentConfig
      tags: [Agents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAgentConfigRequest'
      responses:
        '200':
          description: Updated agent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentDetailResponse'
        '404':
          description: Agent not found
        '423':
          description: Agent is busy

  /agents/delete:
    post:
      summary: Delete an agent
      operationId: deleteAgent
      tags: [Agents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteAgentRequest'
      responses:
        '200':
          description: Agent deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoidResponse'
        '400':
          description: Cannot delete (supervisor with members)
        '404':
          description: Agent not found
        '423':
          description: Agent is busy

  /agents/templates/list:
    post:
      summary: List agent configuration templates
      operationId: listAgentTemplates
      tags: [Agents]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: List of templates
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentTemplateListResponse'

components:
  schemas:
    # Enumerations
    AgentRole:
      type: string
      enum: [GLOBAL_SUPERVISOR, TEAM_SUPERVISOR, WORKER, SCOUTER]
      description: Agent role in hierarchy

    AgentStatus:
      type: string
      enum: [IDLE, THINKING, WORKING, COMPLETED, WAITING, ERROR]
      description: Agent operational status

    # Core DTOs
    AgentDTO:
      type: object
      required: [id, name, role, status, warnings, critical, teamIds, createdAt, updatedAt]
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier
        name:
          type: string
          maxLength: 100
          description: Display name
        role:
          $ref: '#/components/schemas/AgentRole'
        specialty:
          type: string
          maxLength: 200
          nullable: true
          description: Area of expertise
        status:
          $ref: '#/components/schemas/AgentStatus'
        warnings:
          type: integer
          description: Count of warning findings
        critical:
          type: integer
          description: Count of critical findings
        config:
          $ref: '#/components/schemas/AgentConfigDTO'
        teamIds:
          type: array
          items:
            type: integer
            format: int64
          description: IDs of teams this agent belongs to
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    AgentConfigDTO:
      type: object
      required: [model, temperature, systemInstruction]
      properties:
        model:
          type: string
          description: AI model identifier
        temperature:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Creativity parameter
        systemInstruction:
          type: string
          description: System prompt
        defaultContext:
          type: string
          nullable: true
          description: Default context for tasks

    AgentTemplateDTO:
      type: object
      required: [name, description, systemInstruction]
      properties:
        name:
          type: string
          description: Template name
        description:
          type: string
          description: Template description
        recommendedRole:
          $ref: '#/components/schemas/AgentRole'
        systemInstruction:
          type: string
          description: Template system instruction
        recommendedModel:
          type: string
          nullable: true
        recommendedTemperature:
          type: number
          format: float
          nullable: true

    # Request Schemas
    ListAgentsRequest:
      type: object
      properties:
        role:
          $ref: '#/components/schemas/AgentRole'
        teamId:
          type: integer
          format: int64
        keyword:
          type: string
          description: Search by name or specialty
        page:
          type: integer
          default: 1
          minimum: 1
        size:
          type: integer
          default: 10
          minimum: 1
          maximum: 100

    GetAgentRequest:
      type: object
      required: [id]
      properties:
        id:
          type: integer
          format: int64

    CreateAgentRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        role:
          $ref: '#/components/schemas/AgentRole'
        specialty:
          type: string
          maxLength: 200
        config:
          $ref: '#/components/schemas/AgentConfigDTO'

    UpdateAgentRequest:
      type: object
      required: [id]
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 100
        specialty:
          type: string
          maxLength: 200

    UpdateAgentConfigRequest:
      type: object
      required: [id, config]
      properties:
        id:
          type: integer
          format: int64
        config:
          $ref: '#/components/schemas/AgentConfigDTO'

    DeleteAgentRequest:
      type: object
      required: [id]
      properties:
        id:
          type: integer
          format: int64

    # Response Schemas
    ApiResponse:
      type: object
      required: [code, message, success]
      properties:
        code:
          type: integer
          description: Status code (0 = success)
        message:
          type: string
        success:
          type: boolean

    PageResult:
      type: object
      required: [content, page, size, totalElements, totalPages, first, last]
      properties:
        content:
          type: array
          items: {}
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean

    AgentListResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              allOf:
                - $ref: '#/components/schemas/PageResult'
                - type: object
                  properties:
                    content:
                      type: array
                      items:
                        $ref: '#/components/schemas/AgentDTO'

    AgentDetailResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/AgentDTO'

    AgentTemplateListResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/AgentTemplateDTO'

    VoidResponse:
      allOf:
        - $ref: '#/components/schemas/ApiResponse'
        - type: object
          properties:
            data:
              nullable: true
