openapi: 3.0.1
info:
  title: Topology Management API
  description: Topology CRUD and member management endpoints
  version: 1.0.0

paths:
  /api/v1/topologies/query:
    post:
      summary: Query topology list
      operationId: queryTopologies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryTopologiesRequest'
      responses:
        '200':
          description: Query successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResultTopologyDTO'

  /api/v1/topologies/create:
    post:
      summary: Create topology
      operationId: createTopology
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTopologyRequest'
      responses:
        '201':
          description: Created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopologyDTO'
        '409':
          description: Name already exists

  /api/v1/topologies/get:
    post:
      summary: Get topology details
      operationId: getTopology
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetTopologyRequest'
      responses:
        '200':
          description: Query successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopologyDTO'
        '404':
          description: Topology not found

  /api/v1/topologies/update:
    post:
      summary: Update topology
      operationId: updateTopology
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTopologyRequest'
      responses:
        '200':
          description: Update successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopologyDTO'
        '404':
          description: Topology not found
        '409':
          description: Version conflict

  /api/v1/topologies/delete:
    post:
      summary: Delete topology
      operationId: deleteTopology
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteTopologyRequest'
      responses:
        '200':
          description: Delete successful
        '404':
          description: Topology not found

  /api/v1/topologies/members/query:
    post:
      summary: Query topology members
      operationId: queryMembers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryMembersRequest'
      responses:
        '200':
          description: Query successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageResultNodeDTO'

  /api/v1/topologies/members/add:
    post:
      summary: Add members to topology
      operationId: addMembers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddMembersRequest'
      responses:
        '200':
          description: Add successful
        '404':
          description: Topology or node not found

  /api/v1/topologies/members/remove:
    post:
      summary: Remove members from topology
      operationId: removeMembers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveMembersRequest'
      responses:
        '200':
          description: Remove successful
        '404':
          description: Topology not found

components:
  schemas:
    ResourceStatus:
      type: string
      enum: [RUNNING, STOPPED, MAINTENANCE, OFFLINE]

    TopologyDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 500
          nullable: true
        status:
          $ref: '#/components/schemas/ResourceStatus'
        statusDisplay:
          type: string
        coordinatorAgentId:
          type: integer
          format: int64
          nullable: true
        attributes:
          type: string
          nullable: true
        memberCount:
          type: integer
        version:
          type: integer
        createdBy:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    QueryTopologiesRequest:
      type: object
      required: [operatorId]
      properties:
        operatorId:
          type: integer
          format: int64
        name:
          type: string
        status:
          $ref: '#/components/schemas/ResourceStatus'
        page:
          type: integer
          minimum: 1
          default: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
          default: 10

    CreateTopologyRequest:
      type: object
      required: [operatorId, name]
      properties:
        operatorId:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 500

    GetTopologyRequest:
      type: object
      required: [id]
      properties:
        id:
          type: integer
          format: int64

    UpdateTopologyRequest:
      type: object
      required: [operatorId, id, version]
      properties:
        operatorId:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 100
        description:
          type: string
          maxLength: 500
        coordinatorAgentId:
          type: integer
          format: int64
        version:
          type: integer

    DeleteTopologyRequest:
      type: object
      required: [operatorId, id]
      properties:
        operatorId:
          type: integer
          format: int64
        id:
          type: integer
          format: int64

    QueryMembersRequest:
      type: object
      required: [topologyId]
      properties:
        topologyId:
          type: integer
          format: int64
        page:
          type: integer
          minimum: 1
          default: 1
        size:
          type: integer
          minimum: 1
          maximum: 100
          default: 10

    AddMembersRequest:
      type: object
      required: [topologyId, memberIds]
      properties:
        topologyId:
          type: integer
          format: int64
        memberIds:
          type: array
          items:
            type: integer
            format: int64

    RemoveMembersRequest:
      type: object
      required: [topologyId, memberIds]
      properties:
        topologyId:
          type: integer
          format: int64
        memberIds:
          type: array
          items:
            type: integer
            format: int64

    PageResultTopologyDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/TopologyDTO'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean

    PageResultNodeDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/NodeDTO'
        page:
          type: integer
        size:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        first:
          type: boolean
        last:
          type: boolean

    NodeDTO:
      $ref: 'nodes-api.yaml#/components/schemas/NodeDTO'
